/* Generated By:JavaCC: Do not edit this line. BuenaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BuenaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OperadoresAritmeticos = 6;
  /** RegularExpression Id. */
  int OperadoresLogicos = 7;
  /** RegularExpression Id. */
  int ComparacionLogica = 8;
  /** RegularExpression Id. */
  int AlteraTexto = 9;
  /** RegularExpression Id. */
  int Aleatorio = 10;
  /** RegularExpression Id. */
  int Valores = 11;
  /** RegularExpression Id. */
  int Separador = 12;
  /** RegularExpression Id. */
  int MarcadorFinal = 13;
  /** RegularExpression Id. */
  int Escribe = 14;
  /** RegularExpression Id. */
  int Lee = 15;
  /** RegularExpression Id. */
  int Procedimiento = 16;
  /** RegularExpression Id. */
  int FuncionesMatematicas = 17;
  /** RegularExpression Id. */
  int Visible = 18;
  /** RegularExpression Id. */
  int tamVentana = 19;
  /** RegularExpression Id. */
  int Estructura = 20;
  /** RegularExpression Id. */
  int Proteccion = 21;
  /** RegularExpression Id. */
  int Asignacion = 22;
  /** RegularExpression Id. */
  int AsignacionBit = 23;
  /** RegularExpression Id. */
  int AsignacionDesplazamientoBit = 24;
  /** RegularExpression Id. */
  int ParIzquierdo = 25;
  /** RegularExpression Id. */
  int ParDerecho = 26;
  /** RegularExpression Id. */
  int LlaveIzq = 27;
  /** RegularExpression Id. */
  int LlaveDer = 28;
  /** RegularExpression Id. */
  int CorcheteDer = 29;
  /** RegularExpression Id. */
  int CorcheteIzq = 30;
  /** RegularExpression Id. */
  int Ciclos = 31;
  /** RegularExpression Id. */
  int Pregunta = 32;
  /** RegularExpression Id. */
  int PreguntaCondicion = 33;
  /** RegularExpression Id. */
  int Consecuencia = 34;
  /** RegularExpression Id. */
  int AgregaElemento = 35;
  /** RegularExpression Id. */
  int Combina = 36;
  /** RegularExpression Id. */
  int MueveElemento = 37;
  /** RegularExpression Id. */
  int AgregaBorraElemento = 38;
  /** RegularExpression Id. */
  int EliminaElemento = 39;
  /** RegularExpression Id. */
  int Inspecciona = 40;
  /** RegularExpression Id. */
  int Modifica = 41;
  /** RegularExpression Id. */
  int Iteradores = 42;
  /** RegularExpression Id. */
  int Volatil = 43;
  /** RegularExpression Id. */
  int Mutable = 44;
  /** RegularExpression Id. */
  int Treat = 45;
  /** RegularExpression Id. */
  int Registrar = 46;
  /** RegularExpression Id. */
  int Automatico = 47;
  /** RegularExpression Id. */
  int Constante = 48;
  /** RegularExpression Id. */
  int VariableLet = 49;
  /** RegularExpression Id. */
  int VariableGlobal = 50;
  /** RegularExpression Id. */
  int ReduceSobrecarga = 51;
  /** RegularExpression Id. */
  int EvaluaComp = 52;
  /** RegularExpression Id. */
  int EvitaConv = 53;
  /** RegularExpression Id. */
  int NoExcepcion = 54;
  /** RegularExpression Id. */
  int Sobrecarga = 55;
  /** RegularExpression Id. */
  int Operador = 56;
  /** RegularExpression Id. */
  int Referencia = 57;
  /** RegularExpression Id. */
  int GestionTipos = 58;
  /** RegularExpression Id. */
  int DefineEstruct = 59;
  /** RegularExpression Id. */
  int ControlFlujo = 60;
  /** RegularExpression Id. */
  int Salta = 61;
  /** RegularExpression Id. */
  int DevuelveGuarda = 62;
  /** RegularExpression Id. */
  int Alineacion = 63;
  /** RegularExpression Id. */
  int Asercion = 64;
  /** RegularExpression Id. */
  int GestionMemoria = 65;
  /** RegularExpression Id. */
  int GestionTiposCasting = 66;
  /** RegularExpression Id. */
  int ManejoExcepciones = 67;
  /** RegularExpression Id. */
  int EjecutaBloque = 68;
  /** RegularExpression Id. */
  int MetodosFile = 69;
  /** RegularExpression Id. */
  int Excepciones = 70;
  /** RegularExpression Id. */
  int ManejoRutas = 71;
  /** RegularExpression Id. */
  int InstanciasFile = 72;
  /** RegularExpression Id. */
  int MetodosTime = 73;
  /** RegularExpression Id. */
  int InstanciasTime = 74;
  /** RegularExpression Id. */
  int TiposdeDatos = 75;
  /** RegularExpression Id. */
  int MetodoEstatico = 76;
  /** RegularExpression Id. */
  int MetodoVoid = 77;
  /** RegularExpression Id. */
  int MetodoMain = 78;
  /** RegularExpression Id. */
  int Clase = 79;
  /** RegularExpression Id. */
  int Paquete = 80;
  /** RegularExpression Id. */
  int Argumentos = 81;
  /** RegularExpression Id. */
  int Inter = 82;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 83;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "\"\\n\"",
    "<OperadoresAritmeticos>",
    "<OperadoresLogicos>",
    "<ComparacionLogica>",
    "<AlteraTexto>",
    "<Aleatorio>",
    "<Valores>",
    "\",\"",
    "\";\"",
    "<Escribe>",
    "<Lee>",
    "<Procedimiento>",
    "<FuncionesMatematicas>",
    "\"setVisible\"",
    "\"setSize\"",
    "<Estructura>",
    "<Proteccion>",
    "<Asignacion>",
    "<AsignacionBit>",
    "<AsignacionDesplazamientoBit>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"]\"",
    "\"[\"",
    "<Ciclos>",
    "<Pregunta>",
    "\"remove_if\"",
    "<Consecuencia>",
    "<AgregaElemento>",
    "\"merge\"",
    "\"splice\"",
    "\"assign\"",
    "<EliminaElemento>",
    "<Inspecciona>",
    "<Modifica>",
    "<Iteradores>",
    "\"volatile\"",
    "\"mutable\"",
    "\"thread_local\"",
    "\"register\"",
    "\"auto\"",
    "\"const\"",
    "\"let\"",
    "\"var\"",
    "\"inline\"",
    "\"constexpr\"",
    "\"explicit\"",
    "\"noexcept\"",
    "\"override\"",
    "\"operator\"",
    "\"this\"",
    "<GestionTipos>",
    "\"union\"",
    "<ControlFlujo>",
    "\"goto\"",
    "\"yield\"",
    "<Alineacion>",
    "\"static_assert\"",
    "<GestionMemoria>",
    "<GestionTiposCasting>",
    "<ManejoExcepciones>",
    "\"finally\"",
    "<MetodosFile>",
    "<Excepciones>",
    "<ManejoRutas>",
    "<InstanciasFile>",
    "<MetodosTime>",
    "<InstanciasTime>",
    "<TiposdeDatos>",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"class\"",
    "\"Package\"",
    "\"args\"",
    "\"interface\"",
    "<IDENTIFICADOR>",
  };

}
